### 获取订单信息
GET http://localhost:8081/api/payment/1
Accept: */*
Cache-Control: no-cache

### 添加订单信息
POST http://localhost:8081/api/payment
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{"serial":"嘤嘤嘤"}

###